print("  --------------------------------------------------")
naam=input("|  Wat is je naam :")
adres=input("|  Wat is je adres :")
postcode=input("|  wat is je postcode :")
woonplaats=input("|  wat is je wwonplaats :")
print("  --------------------------------------------------")